### ISSUE TITLE
期待更新～

### ISSUE THREAD

**Issue by dodolook8** [1900Star/MusicPlayer-Smartisan#3]
一直想用锤子最新版的音乐播放器，找到了这个包：“Smartisan OS 6.6.6_for ProjectTreble by XiaoHS”，里面的版本是8.1了，而且貌似只能装在锤子手机上，市场上发布的公用版都是n年的老版本了，我的不是锤子手机，所以找到你这里来～
希望能更新下去。谢谢！锤子的音乐播放器是我认为最好看的播放器～

能否给你这个版本加个按文件大小过滤，很多都是手机上的铃声文件，都显示在列表的，很乱。你的版本功能上有点偏少，希望能更新下去～感谢！

**Comment by 1900Star** [comment]
感谢关注！后续有时间我会更新更多功能。

**Comment by 1900Star** [comment]
目前已经增加了文件大小过虑和时长过虑，可以手动选择过虑掉大小小于1M的和时长小于1分钟的歌曲。
